---
- name: Instalar Apache
  apt:
    name: apache2
    state: present

- name: Iniciar el servicio de Apache y asegurarse de que se inicie al arrancar el sistema
  service:
    name: apache2
    state: started
    enabled: yes

- name: Desplegar la página web inicial
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
